name: omnisecure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  workmanager: ^0.5.2
  camera: ^0.10.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
